CREATE OR REPLACE FUNCTION STORE_DATASET.CALCULAR_TOTAL_VENDAS_CLIENTE (CUSTOMER_ID_PARAM INT) 
RETURNS TEXT AS $$

DECLARE
	sales_sum DECIMAL(10, 2);
BEGIN
	SELECT
		SUM(SALE_VALUE) INTO SALES_SUM
	FROM
		STORE_DATASET.SALES
	WHERE
		CUSTOMER_ID = CUSTOMER_ID_PARAM;

	IF sales_sum IS NULL THEN
		RETURN 'Cliente não possui vendas realizadas';
	ELSE
		RETURN 'Total de vendas: ' || sales_sum::MONEY;
	END IF;
END;
$$ LANGUAGE PLPGSQL;

SELECT store_dataset.calcular_total_vendas_cliente(10)

