CREATE TABLE STORE_DATASET.CUSTOMERS (
	CUSTOMER_ID SERIAL PRIMARY KEY,
	CUSTOMER_NAME VARCHAR(255) NOT NULL,
	CUSTOMER_ADDRESS VARCHAR(255),
	CITY VARCHAR(255)
)
	
CREATE TABLE STORE_DATASET.CUSTOMER_ENGAGEMENTS (
	ENGAGEMENT_ID SERIAL PRIMARY KEY,
	CUSTOMER_ID INT NOT NULL,
	ENGAGEMENT_TYPE VARCHAR(60),
	DESCRIPTION TEXT,
	ENGAGEMENT_DATE DATE,
	FOREIGN KEY (CUSTOMER_ID) REFERENCES STORE_DATASET.CUSTOMERS (CUSTOMER_ID)
)
	
CREATE TABLE STORE_DATASET.SALES (
	SALE_ID SERIAL PRIMARY KEY,
	CUSTOMER_ID INT NOT NULL,
	QUANTITY INT NOT NULL,
	SALE_VALUE DECIMAL(10, 2) NOT NULL,
	SALE_DATE DATE,
	FOREIGN KEY (CUSTOMER_ID) REFERENCES STORE_DATASET.CUSTOMERS (CUSTOMER_ID)
)